**Task 1**

Qst 1

In [1]:
def  div(x,y):
  try:
    res=x/y
    print("the result is{}".format(res))
  except ZeroDivisionError:
    print("Divison by zero not possible")
div(5,0)



Divison by zero not possible


Qstn 2

In [6]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["baseball","cricket"]
a=len(subjects)
b=len(verbs)
c=len(objects)
for i in range(0,a):
  for j in range(0,b):
    for k in range(0,c):
      print("{} {} {}".format(subjects[i],verbs[j],objects[k])) 

Americans play baseball
Americans play cricket
Americans watch baseball
Americans watch cricket
Indians play baseball
Indians play cricket
Indians watch baseball
Indians watch cricket


Task 2

Qstn 1

In [14]:
import numpy as np 
matrix=np.array([1,2,3,4])
matrix_size=4
def gen_matrix(matrix,n,inc):
  if inc is False:
    res=np.array([a**(n-i-1) for a in matrix for i in range(n)]).reshape(matrix.size,n)
  else:
    res=np.array([a**i for a in matrix for i in range(n)]).reshape(matrix.size,n)
  return res
res=gen_matrix(matrix,matrix_size,False)
print("Decreasing order:")
print(res)
res=gen_matrix(matrix,matrix_size,True)
print("Increasing order:")
print(res)

Decreasing order:
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
Increasing order:
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
