Write a function to find moving average in an array over a window:          Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [6]:
import numpy as np
def mov_avg(arr,window):
  n=arr.size
  ran=n-window+1
  for i in range(0,ran):
    s=np.around(np.average(arr[i:i+window]),decimals=2)
    print(s)




a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window=3
mov_avg(a,window)



5.0
4.67
5.67
6.67
9.67
28.67
49.33
72.67
84.0
93.33
116.33


Write a function so that the columns of the output matrix are powers of the input  vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.   

In [7]:
import numpy as np 
matrix=np.array([1,2,3,4])
matrix_size=4
def gen_matrix(matrix,n,inc):
  if inc is False:
    res=np.array([a**(n-i-1) for a in matrix for i in range(n)]).reshape(matrix.size,n)
  else:
    res=np.array([a**i for a in matrix for i in range(n)]).reshape(matrix.size,n)
  return res
res=gen_matrix(matrix,matrix_size,False)
print("Decreasing order:")
print(res)
res=gen_matrix(matrix,matrix_size,True)
print("Increasing order:")
print(res)

Decreasing order:
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
Increasing order:
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
